"""esquema inicial

Revision ID: 0001
Revises: 
Create Date: 2026-09-11 15:57:13.514557
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sesiones_demo',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('creada_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ultima_actividad', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sesiones_demo'))
    )
    op.create_index(op.f('ix_sesiones_demo_expira_en'), 'sesiones_demo', ['expira_en'], unique=False)
    op.create_index(op.f('ix_sesiones_demo_ip_hash'), 'sesiones_demo', ['ip_hash'], unique=False)
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id_sesion_demo', sa.String(length=64), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_sesion_demo'], ['sesiones_demo.id'], name=op.f('fk_categorias_id_sesion_demo_sesiones_demo'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categorias'))
    )
    op.create_index(op.f('ix_categorias_id_sesion_demo'), 'categorias', ['id_sesion_demo'], unique=False)
    op.create_index(op.f('ix_categorias_nombre'), 'categorias', ['nombre'], unique=False)
    op.create_index('uq_categorias_nombre_app', 'categorias', ['nombre'], unique=True, postgresql_where=sa.text('id_sesion_demo IS NULL'), sqlite_where=sa.text('id_sesion_demo IS NULL'))
    op.create_index('uq_categorias_nombre_demo', 'categorias', ['nombre', 'id_sesion_demo'], unique=True, postgresql_where=sa.text('id_sesion_demo IS NOT NULL'), sqlite_where=sa.text('id_sesion_demo IS NOT NULL'))
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellido', sa.String(length=80), nullable=True),
    sa.Column('documento', sa.String(length=20), nullable=True),
    sa.Column('cuit', sa.String(length=15), nullable=True),
    sa.Column('telefono', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('direccion', sa.String(length=180), nullable=True),
    sa.Column('localidad', sa.String(length=90), nullable=True),
    sa.Column('notas', sa.String(length=500), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id_sesion_demo', sa.String(length=64), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_sesion_demo'], ['sesiones_demo.id'], name=op.f('fk_clientes_id_sesion_demo_sesiones_demo'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clientes'))
    )
    op.create_index(op.f('ix_clientes_documento'), 'clientes', ['documento'], unique=False)
    op.create_index(op.f('ix_clientes_id_sesion_demo'), 'clientes', ['id_sesion_demo'], unique=False)
    op.create_index(op.f('ix_clientes_nombre'), 'clientes', ['nombre'], unique=False)
    op.create_index('uq_clientes_documento_app', 'clientes', ['documento'], unique=True, postgresql_where=sa.text('id_sesion_demo IS NULL AND documento IS NOT NULL'), sqlite_where=sa.text('id_sesion_demo IS NULL AND documento IS NOT NULL'))
    op.create_index('uq_clientes_documento_demo', 'clientes', ['documento', 'id_sesion_demo'], unique=True, postgresql_where=sa.text('id_sesion_demo IS NOT NULL AND documento IS NOT NULL'), sqlite_where=sa.text('id_sesion_demo IS NOT NULL AND documento IS NOT NULL'))
    op.create_table('medios_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('es_efectivo', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id_sesion_demo', sa.String(length=64), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_sesion_demo'], ['sesiones_demo.id'], name=op.f('fk_medios_pago_id_sesion_demo_sesiones_demo'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medios_pago'))
    )
    op.create_index(op.f('ix_medios_pago_id_sesion_demo'), 'medios_pago', ['id_sesion_demo'], unique=False)
    op.create_index(op.f('ix_medios_pago_nombre'), 'medios_pago', ['nombre'], unique=False)
    op.create_index('uq_medios_pago_nombre_app', 'medios_pago', ['nombre'], unique=True, postgresql_where=sa.text('id_sesion_demo IS NULL'), sqlite_where=sa.text('id_sesion_demo IS NULL'))
    op.create_index('uq_medios_pago_nombre_demo', 'medios_pago', ['nombre', 'id_sesion_demo'], unique=True, postgresql_where=sa.text('id_sesion_demo IS NOT NULL'), sqlite_where=sa.text('id_sesion_demo IS NOT NULL'))
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=160), nullable=False),
    sa.Column('cuit', sa.String(length=15), nullable=True),
    sa.Column('contacto', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('direccion', sa.String(length=180), nullable=True),
    sa.Column('localidad', sa.String(length=90), nullable=True),
    sa.Column('notas', sa.String(length=500), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id_sesion_demo', sa.String(length=64), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_sesion_demo'], ['sesiones_demo.id'], name=op.f('fk_proveedores_id_sesion_demo_sesiones_demo'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proveedores'))
    )
    op.create_index(op.f('ix_proveedores_cuit'), 'proveedores', ['cuit'], unique=False)
    op.create_index(op.f('ix_proveedores_id_sesion_demo'), 'proveedores', ['id_sesion_demo'], unique=False)
    op.create_index(op.f('ix_proveedores_razon_social'), 'proveedores', ['razon_social'], unique=False)
    op.create_index('uq_proveedores_cuit_app', 'proveedores', ['cuit'], unique=True, postgresql_where=sa.text('id_sesion_demo IS NULL AND cuit IS NOT NULL'), sqlite_where=sa.text('id_sesion_demo IS NULL AND cuit IS NOT NULL'))
    op.create_index('uq_proveedores_cuit_demo', 'proveedores', ['cuit', 'id_sesion_demo'], unique=True, postgresql_where=sa.text('id_sesion_demo IS NOT NULL AND cuit IS NOT NULL'), sqlite_where=sa.text('id_sesion_demo IS NOT NULL AND cuit IS NOT NULL'))
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('google_id', sa.String(length=80), nullable=True),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('rol', sa.Enum('PROPIETARIO', 'ENCARGADO', 'VENDEDOR', name='rol', native_enum=False, length=20), nullable=False),
    sa.Column('verificado', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('intentos_fallidos', sa.Integer(), nullable=False),
    sa.Column('bloqueado_hasta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_sesion_demo', sa.String(length=64), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_sesion_demo'], ['sesiones_demo.id'], name=op.f('fk_usuarios_id_sesion_demo_sesiones_demo'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios'))
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=False)
    op.create_index(op.f('ix_usuarios_google_id'), 'usuarios', ['google_id'], unique=False)
    op.create_index(op.f('ix_usuarios_id_sesion_demo'), 'usuarios', ['id_sesion_demo'], unique=False)
    op.create_index('uq_usuarios_email_app', 'usuarios', ['email'], unique=True, postgresql_where=sa.text('id_sesion_demo IS NULL'), sqlite_where=sa.text('id_sesion_demo IS NULL'))
    op.create_index('uq_usuarios_email_demo', 'usuarios', ['email', 'id_sesion_demo'], unique=True, postgresql_where=sa.text('id_sesion_demo IS NOT NULL'), sqlite_where=sa.text('id_sesion_demo IS NOT NULL'))
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('email_usuario', sa.String(length=160), nullable=True),
    sa.Column('accion', sa.String(length=60), nullable=False),
    sa.Column('entidad', sa.String(length=40), nullable=False),
    sa.Column('id_entidad', sa.String(length=40), nullable=True),
    sa.Column('detalle', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], name=op.f('fk_auditoria_id_usuario_usuarios'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auditoria'))
    )
    op.create_index(op.f('ix_auditoria_accion'), 'auditoria', ['accion'], unique=False)
    op.create_index(op.f('ix_auditoria_fecha_hora'), 'auditoria', ['fecha_hora'], unique=False)
    op.create_index(op.f('ix_auditoria_id_usuario'), 'auditoria', ['id_usuario'], unique=False)
    op.create_table('compras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('registrada_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('comprobante', sa.String(length=60), nullable=True),
    sa.Column('notas', sa.String(length=500), nullable=True),
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_sesion_demo', sa.String(length=64), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('total >= 0', name=op.f('ck_compras_total_no_negativo')),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id'], name=op.f('fk_compras_id_proveedor_proveedores')),
    sa.ForeignKeyConstraint(['id_sesion_demo'], ['sesiones_demo.id'], name=op.f('fk_compras_id_sesion_demo_sesiones_demo'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], name=op.f('fk_compras_id_usuario_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compras'))
    )
    op.create_index(op.f('ix_compras_fecha'), 'compras', ['fecha'], unique=False)
    op.create_index(op.f('ix_compras_id_proveedor'), 'compras', ['id_proveedor'], unique=False)
    op.create_index(op.f('ix_compras_id_sesion_demo'), 'compras', ['id_sesion_demo'], unique=False)
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_barra', sa.String(length=50), nullable=True),
    sa.Column('nombre', sa.String(length=140), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('precio_venta', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('precio_costo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_actual', sa.Integer(), nullable=False),
    sa.Column('stock_minimo', sa.Integer(), nullable=False),
    sa.Column('stock_inicial', sa.Integer(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('id_categoria', sa.Integer(), nullable=True),
    sa.Column('id_proveedor', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id_sesion_demo', sa.String(length=64), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('precio_costo >= 0', name=op.f('ck_productos_precio_costo_no_negativo')),
    sa.CheckConstraint('precio_venta >= 0', name=op.f('ck_productos_precio_venta_no_negativo')),
    sa.CheckConstraint('stock_actual >= 0', name=op.f('ck_productos_stock_no_negativo')),
    sa.CheckConstraint('stock_inicial >= 0', name=op.f('ck_productos_stock_inicial_no_negativo')),
    sa.CheckConstraint('stock_minimo >= 0', name=op.f('ck_productos_stock_minimo_no_negativo')),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias.id'], name=op.f('fk_productos_id_categoria_categorias'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id'], name=op.f('fk_productos_id_proveedor_proveedores'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_sesion_demo'], ['sesiones_demo.id'], name=op.f('fk_productos_id_sesion_demo_sesiones_demo'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_productos'))
    )
    op.create_index(op.f('ix_productos_codigo_barra'), 'productos', ['codigo_barra'], unique=False)
    op.create_index(op.f('ix_productos_fecha_vencimiento'), 'productos', ['fecha_vencimiento'], unique=False)
    op.create_index(op.f('ix_productos_id_sesion_demo'), 'productos', ['id_sesion_demo'], unique=False)
    op.create_index(op.f('ix_productos_nombre'), 'productos', ['nombre'], unique=False)
    op.create_index('uq_productos_codigo_barra_app', 'productos', ['codigo_barra'], unique=True, postgresql_where=sa.text('id_sesion_demo IS NULL AND codigo_barra IS NOT NULL'), sqlite_where=sa.text('id_sesion_demo IS NULL AND codigo_barra IS NOT NULL'))
    op.create_index('uq_productos_codigo_barra_demo', 'productos', ['codigo_barra', 'id_sesion_demo'], unique=True, postgresql_where=sa.text('id_sesion_demo IS NOT NULL AND codigo_barra IS NOT NULL'), sqlite_where=sa.text('id_sesion_demo IS NOT NULL AND codigo_barra IS NOT NULL'))
    op.create_table('ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('descuento', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('recibido', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_medio_pago', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('REGISTRADA', 'ANULADA', name='estadoventa', native_enum=False, length=20), nullable=False),
    sa.Column('anulada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_usuario_anulacion', sa.Integer(), nullable=True),
    sa.Column('motivo_anulacion', sa.String(length=255), nullable=True),
    sa.Column('id_sesion_demo', sa.String(length=64), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('descuento >= 0', name=op.f('ck_ventas_descuento_no_negativo')),
    sa.CheckConstraint('recibido IS NULL OR recibido >= total', name=op.f('ck_ventas_recibido_cubre_el_total')),
    sa.CheckConstraint('total >= 0', name=op.f('ck_ventas_total_no_negativo')),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], name=op.f('fk_ventas_id_cliente_clientes')),
    sa.ForeignKeyConstraint(['id_medio_pago'], ['medios_pago.id'], name=op.f('fk_ventas_id_medio_pago_medios_pago')),
    sa.ForeignKeyConstraint(['id_sesion_demo'], ['sesiones_demo.id'], name=op.f('fk_ventas_id_sesion_demo_sesiones_demo'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], name=op.f('fk_ventas_id_usuario_usuarios')),
    sa.ForeignKeyConstraint(['id_usuario_anulacion'], ['usuarios.id'], name=op.f('fk_ventas_id_usuario_anulacion_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ventas'))
    )
    op.create_index(op.f('ix_ventas_estado'), 'ventas', ['estado'], unique=False)
    op.create_index(op.f('ix_ventas_fecha_hora'), 'ventas', ['fecha_hora'], unique=False)
    op.create_index(op.f('ix_ventas_id_cliente'), 'ventas', ['id_cliente'], unique=False)
    op.create_index(op.f('ix_ventas_id_medio_pago'), 'ventas', ['id_medio_pago'], unique=False)
    op.create_index(op.f('ix_ventas_id_sesion_demo'), 'ventas', ['id_sesion_demo'], unique=False)
    op.create_index(op.f('ix_ventas_id_usuario'), 'ventas', ['id_usuario'], unique=False)
    op.create_table('bajas_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Enum('VENCIDO', 'DANADO', 'OTRO', name='motivobaja', native_enum=False, length=20), nullable=False),
    sa.Column('detalle', sa.String(length=255), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id_sesion_demo', sa.String(length=64), nullable=True),
    sa.CheckConstraint('cantidad > 0', name=op.f('ck_bajas_producto_cantidad_positiva')),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], name=op.f('fk_bajas_producto_id_producto_productos')),
    sa.ForeignKeyConstraint(['id_sesion_demo'], ['sesiones_demo.id'], name=op.f('fk_bajas_producto_id_sesion_demo_sesiones_demo'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], name=op.f('fk_bajas_producto_id_usuario_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bajas_producto'))
    )
    op.create_index(op.f('ix_bajas_producto_fecha_hora'), 'bajas_producto', ['fecha_hora'], unique=False)
    op.create_index(op.f('ix_bajas_producto_id_producto'), 'bajas_producto', ['id_producto'], unique=False)
    op.create_index(op.f('ix_bajas_producto_id_sesion_demo'), 'bajas_producto', ['id_sesion_demo'], unique=False)
    op.create_table('compra_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_compra', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('nombre_producto', sa.String(length=140), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id_sesion_demo', sa.String(length=64), nullable=True),
    sa.CheckConstraint('cantidad > 0', name=op.f('ck_compra_items_cantidad_positiva')),
    sa.CheckConstraint('costo_unitario >= 0', name=op.f('ck_compra_items_costo_no_negativo')),
    sa.ForeignKeyConstraint(['id_compra'], ['compras.id'], name=op.f('fk_compra_items_id_compra_compras'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], name=op.f('fk_compra_items_id_producto_productos')),
    sa.ForeignKeyConstraint(['id_sesion_demo'], ['sesiones_demo.id'], name=op.f('fk_compra_items_id_sesion_demo_sesiones_demo'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compra_items'))
    )
    op.create_index(op.f('ix_compra_items_id_compra'), 'compra_items', ['id_compra'], unique=False)
    op.create_index(op.f('ix_compra_items_id_producto'), 'compra_items', ['id_producto'], unique=False)
    op.create_index(op.f('ix_compra_items_id_sesion_demo'), 'compra_items', ['id_sesion_demo'], unique=False)
    op.create_table('movimientos_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('ENTRADA', 'SALIDA', 'AJUSTE', 'VENTA', 'BAJA', 'DEVOLUCION', name='tipomovimiento', native_enum=False, length=20), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('stock_resultante', sa.Integer(), nullable=False),
    sa.Column('nota', sa.String(length=255), nullable=True),
    sa.Column('id_venta', sa.Integer(), nullable=True),
    sa.Column('id_compra', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id_sesion_demo', sa.String(length=64), nullable=True),
    sa.CheckConstraint('cantidad > 0', name=op.f('ck_movimientos_stock_cantidad_positiva')),
    sa.CheckConstraint('stock_resultante >= 0', name=op.f('ck_movimientos_stock_stock_resultante_no_negativo')),
    sa.ForeignKeyConstraint(['id_compra'], ['compras.id'], name=op.f('fk_movimientos_stock_id_compra_compras'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], name=op.f('fk_movimientos_stock_id_producto_productos')),
    sa.ForeignKeyConstraint(['id_sesion_demo'], ['sesiones_demo.id'], name=op.f('fk_movimientos_stock_id_sesion_demo_sesiones_demo'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], name=op.f('fk_movimientos_stock_id_usuario_usuarios')),
    sa.ForeignKeyConstraint(['id_venta'], ['ventas.id'], name=op.f('fk_movimientos_stock_id_venta_ventas'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movimientos_stock'))
    )
    op.create_index('ix_movimientos_producto_fecha', 'movimientos_stock', ['id_producto', 'fecha_hora'], unique=False)
    op.create_index(op.f('ix_movimientos_stock_fecha_hora'), 'movimientos_stock', ['fecha_hora'], unique=False)
    op.create_index(op.f('ix_movimientos_stock_id_sesion_demo'), 'movimientos_stock', ['id_sesion_demo'], unique=False)
    op.create_index(op.f('ix_movimientos_stock_tipo'), 'movimientos_stock', ['tipo'], unique=False)
    op.create_table('venta_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('nombre_producto', sa.String(length=140), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('descuento', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id_sesion_demo', sa.String(length=64), nullable=True),
    sa.CheckConstraint('cantidad > 0', name=op.f('ck_venta_items_cantidad_positiva')),
    sa.CheckConstraint('precio_unitario >= 0', name=op.f('ck_venta_items_precio_unitario_no_negativo')),
    sa.CheckConstraint('subtotal >= 0', name=op.f('ck_venta_items_subtotal_no_negativo')),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], name=op.f('fk_venta_items_id_producto_productos')),
    sa.ForeignKeyConstraint(['id_sesion_demo'], ['sesiones_demo.id'], name=op.f('fk_venta_items_id_sesion_demo_sesiones_demo'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_venta'], ['ventas.id'], name=op.f('fk_venta_items_id_venta_ventas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venta_items'))
    )
    op.create_index(op.f('ix_venta_items_id_producto'), 'venta_items', ['id_producto'], unique=False)
    op.create_index(op.f('ix_venta_items_id_sesion_demo'), 'venta_items', ['id_sesion_demo'], unique=False)
    op.create_index(op.f('ix_venta_items_id_venta'), 'venta_items', ['id_venta'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_venta_items_id_venta'), table_name='venta_items')
    op.drop_index(op.f('ix_venta_items_id_sesion_demo'), table_name='venta_items')
    op.drop_index(op.f('ix_venta_items_id_producto'), table_name='venta_items')
    op.drop_table('venta_items')
    op.drop_index(op.f('ix_movimientos_stock_tipo'), table_name='movimientos_stock')
    op.drop_index(op.f('ix_movimientos_stock_id_sesion_demo'), table_name='movimientos_stock')
    op.drop_index(op.f('ix_movimientos_stock_fecha_hora'), table_name='movimientos_stock')
    op.drop_index('ix_movimientos_producto_fecha', table_name='movimientos_stock')
    op.drop_table('movimientos_stock')
    op.drop_index(op.f('ix_compra_items_id_sesion_demo'), table_name='compra_items')
    op.drop_index(op.f('ix_compra_items_id_producto'), table_name='compra_items')
    op.drop_index(op.f('ix_compra_items_id_compra'), table_name='compra_items')
    op.drop_table('compra_items')
    op.drop_index(op.f('ix_bajas_producto_id_sesion_demo'), table_name='bajas_producto')
    op.drop_index(op.f('ix_bajas_producto_id_producto'), table_name='bajas_producto')
    op.drop_index(op.f('ix_bajas_producto_fecha_hora'), table_name='bajas_producto')
    op.drop_table('bajas_producto')
    op.drop_index(op.f('ix_ventas_id_usuario'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_id_sesion_demo'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_id_medio_pago'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_id_cliente'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_fecha_hora'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_estado'), table_name='ventas')
    op.drop_table('ventas')
    op.drop_index('uq_productos_codigo_barra_demo', table_name='productos', postgresql_where=sa.text('id_sesion_demo IS NOT NULL AND codigo_barra IS NOT NULL'), sqlite_where=sa.text('id_sesion_demo IS NOT NULL AND codigo_barra IS NOT NULL'))
    op.drop_index('uq_productos_codigo_barra_app', table_name='productos', postgresql_where=sa.text('id_sesion_demo IS NULL AND codigo_barra IS NOT NULL'), sqlite_where=sa.text('id_sesion_demo IS NULL AND codigo_barra IS NOT NULL'))
    op.drop_index(op.f('ix_productos_nombre'), table_name='productos')
    op.drop_index(op.f('ix_productos_id_sesion_demo'), table_name='productos')
    op.drop_index(op.f('ix_productos_fecha_vencimiento'), table_name='productos')
    op.drop_index(op.f('ix_productos_codigo_barra'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_compras_id_sesion_demo'), table_name='compras')
    op.drop_index(op.f('ix_compras_id_proveedor'), table_name='compras')
    op.drop_index(op.f('ix_compras_fecha'), table_name='compras')
    op.drop_table('compras')
    op.drop_index(op.f('ix_auditoria_id_usuario'), table_name='auditoria')
    op.drop_index(op.f('ix_auditoria_fecha_hora'), table_name='auditoria')
    op.drop_index(op.f('ix_auditoria_accion'), table_name='auditoria')
    op.drop_table('auditoria')
    op.drop_index('uq_usuarios_email_demo', table_name='usuarios', postgresql_where=sa.text('id_sesion_demo IS NOT NULL'), sqlite_where=sa.text('id_sesion_demo IS NOT NULL'))
    op.drop_index('uq_usuarios_email_app', table_name='usuarios', postgresql_where=sa.text('id_sesion_demo IS NULL'), sqlite_where=sa.text('id_sesion_demo IS NULL'))
    op.drop_index(op.f('ix_usuarios_id_sesion_demo'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_google_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index('uq_proveedores_cuit_demo', table_name='proveedores', postgresql_where=sa.text('id_sesion_demo IS NOT NULL AND cuit IS NOT NULL'), sqlite_where=sa.text('id_sesion_demo IS NOT NULL AND cuit IS NOT NULL'))
    op.drop_index('uq_proveedores_cuit_app', table_name='proveedores', postgresql_where=sa.text('id_sesion_demo IS NULL AND cuit IS NOT NULL'), sqlite_where=sa.text('id_sesion_demo IS NULL AND cuit IS NOT NULL'))
    op.drop_index(op.f('ix_proveedores_razon_social'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_id_sesion_demo'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_cuit'), table_name='proveedores')
    op.drop_table('proveedores')
    op.drop_index('uq_medios_pago_nombre_demo', table_name='medios_pago', postgresql_where=sa.text('id_sesion_demo IS NOT NULL'), sqlite_where=sa.text('id_sesion_demo IS NOT NULL'))
    op.drop_index('uq_medios_pago_nombre_app', table_name='medios_pago', postgresql_where=sa.text('id_sesion_demo IS NULL'), sqlite_where=sa.text('id_sesion_demo IS NULL'))
    op.drop_index(op.f('ix_medios_pago_nombre'), table_name='medios_pago')
    op.drop_index(op.f('ix_medios_pago_id_sesion_demo'), table_name='medios_pago')
    op.drop_table('medios_pago')
    op.drop_index('uq_clientes_documento_demo', table_name='clientes', postgresql_where=sa.text('id_sesion_demo IS NOT NULL AND documento IS NOT NULL'), sqlite_where=sa.text('id_sesion_demo IS NOT NULL AND documento IS NOT NULL'))
    op.drop_index('uq_clientes_documento_app', table_name='clientes', postgresql_where=sa.text('id_sesion_demo IS NULL AND documento IS NOT NULL'), sqlite_where=sa.text('id_sesion_demo IS NULL AND documento IS NOT NULL'))
    op.drop_index(op.f('ix_clientes_nombre'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_id_sesion_demo'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_documento'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index('uq_categorias_nombre_demo', table_name='categorias', postgresql_where=sa.text('id_sesion_demo IS NOT NULL'), sqlite_where=sa.text('id_sesion_demo IS NOT NULL'))
    op.drop_index('uq_categorias_nombre_app', table_name='categorias', postgresql_where=sa.text('id_sesion_demo IS NULL'), sqlite_where=sa.text('id_sesion_demo IS NULL'))
    op.drop_index(op.f('ix_categorias_nombre'), table_name='categorias')
    op.drop_index(op.f('ix_categorias_id_sesion_demo'), table_name='categorias')
    op.drop_table('categorias')
    op.drop_index(op.f('ix_sesiones_demo_ip_hash'), table_name='sesiones_demo')
    op.drop_index(op.f('ix_sesiones_demo_expira_en'), table_name='sesiones_demo')
    op.drop_table('sesiones_demo')
    # ### end Alembic commands ###
