"""codigos de verificacion y recuperacion

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-11 17:55:09.406649
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codigos_unicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('codigo_hash', sa.String(length=64), nullable=False),
    sa.Column('tipo', sa.Enum('VERIFICACION', 'RECUPERACION', name='tipocodigo', native_enum=False, length=20), nullable=False),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=False),
    sa.Column('intentos', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_codigos_unicos'))
    )
    op.create_index(op.f('ix_codigos_unicos_email'), 'codigos_unicos', ['email'], unique=False)
    op.create_index(op.f('ix_codigos_unicos_expira_en'), 'codigos_unicos', ['expira_en'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_codigos_unicos_expira_en'), table_name='codigos_unicos')
    op.drop_index(op.f('ix_codigos_unicos_email'), table_name='codigos_unicos')
    op.drop_table('codigos_unicos')
    # ### end Alembic commands ###
